---
title: "Rolling Protective Put"
author: Xiaoxiang Shan
class: Simulation Application
professor: Chidambaran

---

```{r}
# Random number generator
MYUNIFORM <- function(inputvar)
{
  idum <- inputvar[1]
  numran <- inputvar[2]
  IM1 <- 2147483563
  IM2 <- 2147483399
  IMM1 <- IM1-1
  IA1 <- 40014
  IA2 <- 40692
  IQ1 <- 53668 
  IQ2 <- 52774
  IR1 <- 12211
  IR2 <- 3791
  NTAB <- 32
  NDIV <- as.integer(1+IMM1/NTAB)
  AM=1.0/IM1
  EPS=1.2e-7
  RNMX=1.-EPS
  iv=rep(0,NTAB)
  idum2 <- 123456789
  iy <- 0
  ranx <- rep(0,numran)
  icount <- 1
  for (icount in 1:numran)
  {
    if (idum<=0)
    {
      idum<-max(-idum,1)
      idum2 <- idum
      j<-NTAB+8
      while (j>0)
      {
        k <- as.integer(idum/IQ1)
        idum<-IA1*(idum-k*IQ1)-k*IR1
        if (idum<0){idum <- idum+IM1}
        if(j<= NTAB){iv[j] <- idum}
        j <- j-1
      }
      iy <- iv[1]
    }
    k<-as.integer(idum/IQ1)
    idum<-IA1*(idum-k*IQ1)-k*IR1
    if (idum<0) {idum <- idum+IM1}
    k<-as.integer(idum2/IQ2)
    idum2<-IA2*(idum2-k*IQ2)-k*IR2
    if (idum2<0) {idum2 <- idum2+IM2}
    j<-as.integer(iy/NDIV)+1
    iy<-iv[j]-idum2
    iv[j]<-idum
    if (iy<1) {iy<-iy+IMM1}
    ran2<-min(AM*iy,RNMX)
    ranx[icount]<-ran2
    icount<-icount+1
  }
  
  return(ranx)
}
```


```{r}
# Normal dist generator
MYNORM <- function(ran_c)
{
  a0 <- 2.50662823884
  a1 <- -18.61500062529
  a2 <- 41.39119773534
  a3 <- -25.44106049637

  b0 <- -8.47351093090
  b1 <- 23.08336743743
  b2 <- -21.06224101826
  b3 <- 3.13082909833
  
  c0 <- 0.3374754822726147
  c1 <- 0.9761690190917186
  c2 <- 0.1607979714918209
  c3 <- 0.0276438810333863
  c4 <- 0.0038405729373609
  c5 <- 0.0003951896511919
  c6 <- 0.0000321767881768
  c7 <- 0.0000002888167364
  c8 <- 0.0000003960315187
  
  jcount <- 1
  numran <- inputvar[2]
  ran_norm_c <- rep(0,numran)
  while(jcount <= numran)
  {
    u <- ran_c[jcount]
    y <- u-0.5
    if(abs(y)<0.42)
    {
      r <- y*y
      x <- y*(((a3*r+a2)*r+a1)*r+a0)/((((b3*r+b2)*r+b1)*r+b0)*r+1)
    }
    else
    {
      r <- u
      if(y>0){r <- 1-u}
      r <- log(-log(r))
      x <- c0+r*(c1+r*(c2+r*(c3+r*(c4+r*(c5+r*(c6+r*(c7+r*c8)))))))
      if(y<0){x <- -x}
    }
    ran_norm_c[jcount] <- x
    jcount <- jcount+1
  } 
  return(ran_norm_c)
}
```

```{r}
seed <- 0
numran <- 500000
inputvar <- c(seed,numran)
ran_uniform_c <- MYUNIFORM(inputvar)
rand_norm <- MYNORM(ran_uniform_c)
#seed <- 1000
#numran <- 500000
#inputvar <- c(seed,numran)
#ran_uniform_c <- MYUNIFORM(inputvar)
#rand_norm2 <- MYNORM(ran_uniform_c)
```

```{r}
# Price Paths and Average
PricePath <- function(drift, Volatility, rand_norm)
{
  S0 <- 100
  rf <- 0.02
  T <- 1
  dt <- 1/12
  numpath <- 10000
  ST_Vals <- matrix(rep(0),nrow=13,ncol=numpath)
  ST_Rets <- rep(0,numpath)
  #ST_Vals_avg <- rep(0,numpath)
  jcount <- 1
  lcount <- 1
  while(jcount<=numpath)
  {
    St <- S0
    #ST_avg <- 0
    for (kcount in 1:13)
    {
      #exp(miu*dt+sigma*sqrt(dt)*normn[lcount])
      St <-St*exp(drift*dt+Volatility*sqrt(dt)*rand_norm[lcount])
      ST_Vals[kcount,jcount] <- St
      lcount <- lcount+1
    }
    #ST_Rets[jcount] <- log(ST_Vals[13,jcount]/S0)
    jcount = jcount+1
  }
  #theoritical_mean <- exp(drift)*sqrt(exp(Volatility*Volatility)-1)
  #sample_mean <- mean(ST_Rets)
  #theoritical_mean;
  #sample_mean;

  return (ST_Vals)
}
```

```{r}
BS <- function(S0,K,Vol,T)
{
  rf <- 0.02
  d1 <- (log(S0/K)+(rf+0.5*Vol*Vol)*T)/(Vol*sqrt(T))
  d2 <- d1-Vol*sqrt(T)
  Nd1 <- pnorm(-d1,mean=0,sd=1)
  Nd2 <- pnorm(-d2,mean=0,sd=1)
  P <- K*exp(-rf*T)*Nd2-S0*Nd1
  return (P)
}
```

```{r}

Prot_Put <- function(pct_K,vol,ST_Vals)
{
  S0<-100
  numpath<-10000
  payoff<-rep(0,numpath)
  r <- 0.02
  ST <- ST_Vals[13,]
  for(i in 1:numpath)
  {
    rollin<- -BS(S0,(1+pct_K)*S0,vol,3/12)
    payoff[i]<- payoff[i]+rollin*exp(r*1) 
    for(j in 2:12)
    {
      rollin = -BS(ST_Vals[j,i],(1+pct_K)*ST_Vals[j,i],vol,3/12)
      rollout= BS(ST_Vals[j,i],(1+pct_K)*ST_Vals[j-1,i],vol,2/12)
      payoff[i]=payoff[i] + (rollin+rollout)*exp(r*(1-(j-1)/12))
    }
    rollout=BS(ST_Vals[13,i],(1+pct_K)*ST_Vals[12,i],vol,2/12)
    payoff[i]=payoff[i] + rollout
  }
  payoff=payoff+ST-rep(100,numpath)
  #mean(payoff)
  #mean_return[trial_number]<-mean(payoff)
  #std_return[trial_number]<-sd(payoff)
  
  #return(mean_return[trial_number])
  return(c(mean(payoff),sd(payoff)))
}

```

```{r}
# Outputs
mean_return<-rep(0,8)
sd_return<-rep(0,8)
# drift 8%, vol 20%, 5% ITM put
ST_Vals <- PricePath(0.08,0.2,rand_norm)
mean_return[1]<- Prot_Put(0.05,0.2,ST_Vals)[1]
sd_return[1] <- Prot_Put(0.05,0.2,ST_Vals)[2]

# drift 12%, vol 20%, 5% ITM put
ST_Vals <- PricePath(0.12,0.2,rand_norm)
mean_return[2] <-Prot_Put(0.05,0.2,ST_Vals)[1]
sd_return[2] <-Prot_Put(0.05,0.2,ST_Vals)[2]

# drift 8%, vol 30%, 5% ITM put
ST_Vals <- PricePath(0.12,0.2,rand_norm)
mean_return[3] <-Prot_Put(0.05,0.2,ST_Vals)[1]
sd_return[3] <-Prot_Put(0.05,0.2,ST_Vals)[2]

# drift 12%, vol 30%, 5% ITM put
ST_Vals <- PricePath(0.12,0.2,rand_norm)
mean_return[4] <-Prot_Put(0.05,0.2,ST_Vals)[1]
sd_return[4] <-Prot_Put(0.05,0.2,ST_Vals)[2]

# drift 8%, vol 20%, 5% OTM put
ST_Vals <- PricePath(0.08,0.2,rand_norm)
mean_return[5] <-Prot_Put(-0.05,0.2,ST_Vals)[1]
sd_return[5] <-Prot_Put(-0.05,0.2,ST_Vals)[2]

# drift 12%, vol 20%, 5% OTM put
ST_Vals <- PricePath(0.12,0.2,rand_norm)
mean_return[6] <-Prot_Put(-0.05,0.2,ST_Vals)[1]
sd_return[6] <-Prot_Put(-0.05,0.2,ST_Vals)[2]

# drift 8%, vol 30%, 5% OTM put
ST_Vals <- PricePath(0.12,0.2,rand_norm)
mean_return[7] <-Prot_Put(-0.05,0.2,ST_Vals)[1]
sd_return[7] <-Prot_Put(-0.05,0.2,ST_Vals)[2]

# drift 12%, vol 30%, 5% OTM put
ST_Vals <- PricePath(0.12,0.2,rand_norm)
mean_return[8] <-Prot_Put(-0.05,0.2,ST_Vals)[1]
sd_return[8] <-Prot_Put(-0.05,0.2,ST_Vals)[2]

result<-t(matrix(c(mean_return,sd_return),nrow = 8))
table<-as.table(result)
row.names(table)=c("Mean of Return","Standard Deviation of Return")
colnames(table)<-c("0.08/0.2/105","0.12/0.2/105","0.08/0.3/105","0.12/0.3/105","0.08/0.2/95","0.12/0.2/95","0.08/0.3/95","0.12/0.3/95")
table

```

