---
title: "Bond Option"
author: Xiaoxiang Shan
class: Simulation Application
professor: Chidambaran
---

```{r}
# Random number generator
MYUNIFORM <- function(inputvar)
{
  idum <- inputvar[1]
  numran <- inputvar[2]
  IM1 <- 2147483563
  IM2 <- 2147483399
  IMM1 <- IM1-1
  IA1 <- 40014
  IA2 <- 40692
  IQ1 <- 53668 
  IQ2 <- 52774
  IR1 <- 12211
  IR2 <- 3791
  NTAB <- 32
  NDIV <- as.integer(1+IMM1/NTAB)
  AM=1.0/IM1
  EPS=1.2e-7
  RNMX=1.-EPS
  iv=rep(0,NTAB)
  idum2 <- 123456789
  iy <- 0
  ranx <- rep(0,numran)
  icount <- 1
  for (icount in 1:numran)
  {
    if (idum<=0)
    {
      idum<-max(-idum,1)
      idum2 <- idum
      j<-NTAB+8
      while (j>0)
      {
        k <- as.integer(idum/IQ1)
        idum<-IA1*(idum-k*IQ1)-k*IR1
        if (idum<0){idum <- idum+IM1}
        if(j<= NTAB){iv[j] <- idum}
        j <- j-1
      }
      iy <- iv[1]
    }
    k<-as.integer(idum/IQ1)
    idum<-IA1*(idum-k*IQ1)-k*IR1
    if (idum<0) {idum <- idum+IM1}
    k<-as.integer(idum2/IQ2)
    idum2<-IA2*(idum2-k*IQ2)-k*IR2
    if (idum2<0) {idum2 <- idum2+IM2}
    j<-as.integer(iy/NDIV)+1
    iy<-iv[j]-idum2
    iv[j]<-idum
    if (iy<1) {iy<-iy+IMM1}
    ran2<-min(AM*iy,RNMX)
    ranx[icount]<-ran2
    icount<-icount+1
  }
  
  return(ranx)
}
```


```{r}
# Normal dist generator
MYNORM <- function(ran_c)
{
  a0 <- 2.50662823884
  a1 <- -18.61500062529
  a2 <- 41.39119773534
  a3 <- -25.44106049637

  b0 <- -8.47351093090
  b1 <- 23.08336743743
  b2 <- -21.06224101826
  b3 <- 3.13082909833
  
  c0 <- 0.3374754822726147
  c1 <- 0.9761690190917186
  c2 <- 0.1607979714918209
  c3 <- 0.0276438810333863
  c4 <- 0.0038405729373609
  c5 <- 0.0003951896511919
  c6 <- 0.0000321767881768
  c7 <- 0.0000002888167364
  c8 <- 0.0000003960315187
  
  jcount <- 1
  numran <- inputvar[2]
  ran_norm_c <- rep(0,numran)
  while(jcount <= numran)
  {
    u <- ran_c[jcount]
    y <- u-0.5
    if(abs(y)<0.42)
    {
      r <- y*y
      x <- y*(((a3*r+a2)*r+a1)*r+a0)/((((b3*r+b2)*r+b1)*r+b0)*r+1)
    }
    else
    {
      r <- u
      if(y>0){r <- 1-u}
      r <- log(-log(r))
      x <- c0+r*(c1+r*(c2+r*(c3+r*(c4+r*(c5+r*(c6+r*(c7+r*c8)))))))
      if(y<0){x <- -x}
    }
    ran_norm_c[jcount] <- x
    jcount <- jcount+1
  } 
  return(ran_norm_c)
}
```

```{r}
seed <- 0
numran <- 500000
inputvar <- c(seed,numran)
ran_uniform_c <- MYUNIFORM(inputvar)
normn <- MYNORM(ran_uniform_c)
```

```{r}
#vasicek model
#Bond Price
bond<-function(alpha,u,sigma)
{
  A<-c()
  C<-c()
  for(t in 1:5)
  {
    A[t]<-(1-exp(-alpha*t))/alpha
    C[t]<-(u-0.5*sigma^2/alpha^2-sigma/alpha)*(t-A[t])+sigma^2*A[t]^2/(4*alpha)
  }
  r0<-0.07
  return(exp(-r0*A-C))
}
```

```{r}
#Residual Sum Square
SSR<-function(para)
{
  model_price<-bond(para[1],para[2],para[3])
  market_price<-c()
  sum<-0
  for(i in 1:5){
    market_price[i]<-1/(r[i]+1)^i
    sum<-sum+(market_price[i]-model_price[i])^2
  }
  return(sum)
}
```

```{r}
Coupon<-7.25
Face<-100
r<-c(0.07,0.07,0.07,0.07,0.07)
price<-0
for(i in 1:5)
{
  price<-price+Coupon*exp(-i*r[i])
}
bond_price<-price+Face*exp(-5*r[5])

para<-optim(c(0.2,0.01,0.05),SSR)$par #to minimize ssr
alpha<-para[1]
u<-para[2]
sigma<-para[3]

numpath<-10000
jcount<-1
lcount<-1
r_path<-matrix(rep(0.01),nrow=5,ncol=numpath)
#Simulate yield
while(jcount<numpath){
  for(i in 2:5){
    r_path[i,jcount]<-r_path[i-1,jcount]*exp(-alpha)+u*(1-exp(-alpha))+(0.5*sigma^2/alpha)*(1-exp(-2*alpha))*normn[lcount]
    lcount<- lcount+1
  }
  jcount= jcount+1
}

payoff<-rep(0,numpath)
for(i in 1:numpath){
  B_price<-0
  discount_factor<-1
  for(j in 2:5){
    discount_factor<-discount_factor/(1+r_path[j,i])
    B_price<-B_price+Coupon*discount_factor
  }
  B_price<-B_price+Face*discount_factor
  payoff[i]<-max(B_price-100,0)/(1+r[1])
}
option_price<-mean(payoff)

option_price
```


